name: 'test-action'
description: 'Test action'
author: 'Roland Warburton'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    require: true

runs:
  using: 'node16'
  main: 'app/dist/index.js'
