name: on-pull-request

on: ['pull_request']

jobs:
  run-js-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install and run test
        working-directory: ./lib
        run: |
          npm install
          npm run test
