name: Test

on: ['push']

jobs:
  test-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
        ls ${{ github.workspace }} &&\
        echo "The following files are in the repository:"
      - run: echo "This job's status is ${{ job.status }}."
